<?php

/**
 * Class in charge to manage messages generated by app.
 * It is important because if maybe a translation is required.
 * @package default
 */

class messages{

	//Class Attributes
	private $current_message = '';
	private $messages        = array(
								'general' => array(
									'ok' => array(
										'Command OK',
										),
									),
									'error' => array(
										),
								'canvas' => array(
									'ok' => array(
										),
									'error' => array(
										'Command Error : Size of canvas cannot be less than 1 x 1 or greater than 100 x 20',
										),
									),
								'line' => array(
									'ok' => array(
										),
									'error' => array(
										'Line cannot be printed between given coordinates',
										'Create a canvas first',
										),
									),
								'rec' => array(
									'ok' => array(
										),
									'error' => array(
										'Rectangle cannot be created',
										),
									),
								);

	/**
	 * This function translate a key in a message saved in the attribute $messages.
	 * @param string $key 
	 * @return boolean
	 */
	public function set_message( $key = '' ){
		$message_array = explode('-', $key);
		$this->current_message = $this->messages[$message_array[0]][$message_array[1]][$message_array[2]];
		return true;
	}

	/**
	 * This function returns the welcome message for the user (help message)
	 * @param boolean $reload 
	 * @return string
	 */
	public function get_init_message(){
		return "Quick help:
C N N :		Command C creates a canvas of NxN
L N N M M :	Command L draws a line from point (N,N) until (M,M) inside of canvas
R N N M M :	Command R draws a rectangle from point (N,N) until (M,M) inside of canvas
B N N char:	Command B fills the space arround point (N,N) with character char";
	}

	/**
	 * This function is in charge to return the value saved in the attribute $current_message
	 * @return string
	 */
	public function get_current_message(){
		return $this->current_message;
	}

}
